package com.unican.gist.gistus.domain.Objects;

import com.ajithvgiri.searchdialog.SearchListItem;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by Andres on 16/03/2018.
 */

public class AllStops {
    private List<SearchListItem> searchListItems = new ArrayList<>();

    public List<SearchListItem> devuelveLista() {
        searchListItems.add(new SearchListItem(511, "Intercambiador del Sardinero 1"));
        searchListItems.add(new SearchListItem(516, "Intercambiador del Sardinero"));
        searchListItems.add(new SearchListItem(443, "El Mazo S/N"));
        searchListItems.add(new SearchListItem(447, "Ojaiz 166"));
        searchListItems.add(new SearchListItem(446, "Ojaiz 89"));
        searchListItems.add(new SearchListItem(470, "General Davila. 77"));
        searchListItems.add(new SearchListItem(471, "Calle Arriba 64"));
        searchListItems.add(new SearchListItem(473, "Ricardo Leon"));
        searchListItems.add(new SearchListItem(479, "Marques de Hazas - 1"));
        searchListItems.add(new SearchListItem(480, "Marques de Hazas - 2"));
        searchListItems.add(new SearchListItem(481, "Jeronimo Sainz de la Maza ( Mercado Mexico )"));
        searchListItems.add(new SearchListItem(509, "Intercambiador deValdecilla"));
        searchListItems.add(new SearchListItem(463, "La Pereda 14"));
        searchListItems.add(new SearchListItem(490, "C/ Adarzo.48"));
        searchListItems.add(new SearchListItem(499, "Camarreal PeÇñacastillo"));
        searchListItems.add(new SearchListItem(500, "Ortega y Gasset.28"));
        searchListItems.add(new SearchListItem(505, "Avenida de Cantabria nº 35"));
        searchListItems.add(new SearchListItem(506, "Avenida de Cantabria nº 76"));
        searchListItems.add(new SearchListItem(510, "Jesus de Monasterio 7"));
        searchListItems.add(new SearchListItem(517, "Los Agustinos"));
        searchListItems.add(new SearchListItem(515, "Intercambiador del Sardinero 2"));
        searchListItems.add(new SearchListItem(512, "Intercambiador de Avenida de Valdecilla"));
        searchListItems.add(new SearchListItem(482, "Luis Quintanilla Isasi"));
        searchListItems.add(new SearchListItem(483, "Gerardo Diego - 1"));
        searchListItems.add(new SearchListItem(487, "Pctcan - 3"));
        searchListItems.add(new SearchListItem(489, "Albert Einstein.14"));
        searchListItems.add(new SearchListItem(488, "Pctcan"));
        searchListItems.add(new SearchListItem(491, "C/ Adarzo.117"));
        searchListItems.add(new SearchListItem(498, "Carmen Bravo Villasante.1"));
        searchListItems.add(new SearchListItem(504, "Tetuan . 41"));
        searchListItems.add(new SearchListItem(507, "Virgen del Mar"));
        searchListItems.add(new SearchListItem(508, "Calle Rucandial"));
        searchListItems.add(new SearchListItem(454, "Pctcan - 1"));
        searchListItems.add(new SearchListItem(455, "Adarzo"));
        searchListItems.add(new SearchListItem(448, "Valdecilla Sur"));
        searchListItems.add(new SearchListItem(449, "Valdecilla Sur"));
        searchListItems.add(new SearchListItem(451, "Hermanos Calderon"));
        searchListItems.add(new SearchListItem(456, "Cervantes 29"));
        searchListItems.add(new SearchListItem(465, "Avenida del Deporte . 9"));
        searchListItems.add(new SearchListItem(466, "Bº La Sierra"));
        searchListItems.add(new SearchListItem(467, "Vicente Trueba"));
        searchListItems.add(new SearchListItem(468, "Vicente Trueba"));
        searchListItems.add(new SearchListItem(469, "Bº La Sierra nº 10"));
        searchListItems.add(new SearchListItem(486, "Pctcan - 2"));
        searchListItems.add(new SearchListItem(492, "Centro de Salud Nueva MontaÇña"));
        searchListItems.add(new SearchListItem(493, "Gertrudis Gomez de Avellaneda"));
        searchListItems.add(new SearchListItem(494, "Eusebio Santamaria.1"));
        searchListItems.add(new SearchListItem(495, "Eusebio Santamaria.2"));
        searchListItems.add(new SearchListItem(496, "Eusebio Santamaria"));
        searchListItems.add(new SearchListItem(497, "Carmen Bravo Villasante"));
        searchListItems.add(new SearchListItem(299, "Bartolome Darnis"));
        searchListItems.add(new SearchListItem(300, "Colegio Nueva MontaÇña"));
        searchListItems.add(new SearchListItem(301, "Santiago el Mayor 10"));
        searchListItems.add(new SearchListItem(302, "San Martin del Pino 1"));
        searchListItems.add(new SearchListItem(303, "San Martin del Pino 23"));
        searchListItems.add(new SearchListItem(304, "Institutos"));
        searchListItems.add(new SearchListItem(305, "Carrefour PeÇñacastillo"));
        searchListItems.add(new SearchListItem(306, "Francisco Rivas Moreno"));
        searchListItems.add(new SearchListItem(464, "La Pereda "));
        searchListItems.add(new SearchListItem(502, "Barrio Camino . 27"));
        searchListItems.add(new SearchListItem(503, "Centro de Salud"));
        searchListItems.add(new SearchListItem(445, "LLuja - Cementerio"));
        searchListItems.add(new SearchListItem(200, "Consuelo BergÇ¸s 16"));
        searchListItems.add(new SearchListItem(478, "PeÇñacastillo - Camarreal"));
        searchListItems.add(new SearchListItem(474, "Avenida del Voluntariado"));
        searchListItems.add(new SearchListItem(475, "Ricardo Lopez Aranda"));
        searchListItems.add(new SearchListItem(476, "Jose Ortega y Gasset - 1"));
        searchListItems.add(new SearchListItem(477, "Jose Ortega y Gasset - 2"));
        searchListItems.add(new SearchListItem(457, "Calle del Monte 12"));
        searchListItems.add(new SearchListItem(459, "Veridiano Rojo"));
        searchListItems.add(new SearchListItem(461, "Menendez Pelayo 25"));
        searchListItems.add(new SearchListItem(462, "Jorge Sepulveda 2"));
        searchListItems.add(new SearchListItem(411, "Maria Blanchar"));
        searchListItems.add(new SearchListItem(412, "La cavaduca"));
        searchListItems.add(new SearchListItem(413, "La Albericia 1"));
        searchListItems.add(new SearchListItem(414, "La Gloria 8"));
        searchListItems.add(new SearchListItem(415, "La Gloria 60"));
        searchListItems.add(new SearchListItem(416, "La Gloria 120"));
        searchListItems.add(new SearchListItem(417, "La Gloria144"));
        searchListItems.add(new SearchListItem(418, "La Gloria 234"));
        searchListItems.add(new SearchListItem(420, "La Gloria 163"));
        searchListItems.add(new SearchListItem(421, "La Gloria 157"));
        searchListItems.add(new SearchListItem(422, "La Gloria 123"));
        searchListItems.add(new SearchListItem(423, "La Gloria 43"));
        searchListItems.add(new SearchListItem(424, "La Gloria 1"));
        searchListItems.add(new SearchListItem(265, "Perez Galdos 4"));
        searchListItems.add(new SearchListItem(267, "Perez Galdos 36"));
        searchListItems.add(new SearchListItem(268, "Calle Alta Mercado"));
        searchListItems.add(new SearchListItem(269, "Calle Alta 109"));
        searchListItems.add(new SearchListItem(270, "Calle Alta 81"));
        searchListItems.add(new SearchListItem(271, "Calle Alta 45"));
        searchListItems.add(new SearchListItem(272, "Monte Caloca"));
        searchListItems.add(new SearchListItem(92, "Jeronimo Saiz de la Maza"));
        searchListItems.add(new SearchListItem(93, "Candina"));
        searchListItems.add(new SearchListItem(294, "Avenida Parayas Mercedes"));
        searchListItems.add(new SearchListItem(296, "Abilio Garcia baron 1 ( hote4l expres)"));
        searchListItems.add(new SearchListItem(298, "Francisco Tomas y Valiente 7"));
        searchListItems.add(new SearchListItem(378, "Cruce Aviche"));
        searchListItems.add(new SearchListItem(379, "Aviche 37"));
        searchListItems.add(new SearchListItem(380, "Canteros de Transmiera 2"));
        searchListItems.add(new SearchListItem(382, "Caleruco 5"));
        searchListItems.add(new SearchListItem(385, "Corbanera 39"));
        searchListItems.add(new SearchListItem(383, "Corbanera 53"));
        searchListItems.add(new SearchListItem(384, "Corbanera"));
        searchListItems.add(new SearchListItem(386, "Corbanera 93"));
        searchListItems.add(new SearchListItem(390, "La Albericia 18"));
        searchListItems.add(new SearchListItem(393, "Maria Blanchar"));
        searchListItems.add(new SearchListItem(394, "Instituto La Albericia"));
        searchListItems.add(new SearchListItem(395, "Casa Del Deporte"));
        searchListItems.add(new SearchListItem(396, "CorceÇño"));
        searchListItems.add(new SearchListItem(398, "Ambulatorio"));
        searchListItems.add(new SearchListItem(399, "Barrio El Somo 78"));
        searchListItems.add(new SearchListItem(400, "Barrio El Somo 30"));
        searchListItems.add(new SearchListItem(401, "Corban"));
        searchListItems.add(new SearchListItem(402, "Ciriego"));
        searchListItems.add(new SearchListItem(403, "Corban"));
        searchListItems.add(new SearchListItem(404, "El Mazo 30"));
        searchListItems.add(new SearchListItem(405, "El Mazo 2"));
        searchListItems.add(new SearchListItem(406, "Barrio El Somo 43"));
        searchListItems.add(new SearchListItem(407, "Barrio El Somo 37"));
        searchListItems.add(new SearchListItem(408, "El Somo"));
        searchListItems.add(new SearchListItem(409, "CorceÇño 69"));
        searchListItems.add(new SearchListItem(365, "Caleruco"));
        searchListItems.add(new SearchListItem(367, "Grupo Ateca"));
        searchListItems.add(new SearchListItem(368, "Iglesia"));
        searchListItems.add(new SearchListItem(369, "San Pedro Del Mar 64"));
        searchListItems.add(new SearchListItem(60, "El Empalme"));
        searchListItems.add(new SearchListItem(290, "Avenida de Cantabria nº 28"));
        searchListItems.add(new SearchListItem(266, "Perez Galdos nº 18"));
        searchListItems.add(new SearchListItem(121, "General Davila 89"));
        searchListItems.add(new SearchListItem(143, "General Davila 266"));
        searchListItems.add(new SearchListItem(334, "Cruce con Rucandial"));
        searchListItems.add(new SearchListItem(297, "Autonomia 8"));
        searchListItems.add(new SearchListItem(336, "Autonomia 3"));
        searchListItems.add(new SearchListItem(335, "Autonomia 9"));
        searchListItems.add(new SearchListItem(370, "Corbanera 93"));
        searchListItems.add(new SearchListItem(371, "El Castillo"));
        searchListItems.add(new SearchListItem(372, "Corbanera 162"));
        searchListItems.add(new SearchListItem(373, "El Parque"));
        searchListItems.add(new SearchListItem(374, "San Pedro Del Mar 91"));
        searchListItems.add(new SearchListItem(375, "Barrio Bolado 23"));
        searchListItems.add(new SearchListItem(376, "Barrio Bolado 37"));
        searchListItems.add(new SearchListItem(377, "Barrio Bolado 58"));
        searchListItems.add(new SearchListItem(397, "Barrio El Somo"));
        searchListItems.add(new SearchListItem(171, "Alcalde vega lamera 1"));
        searchListItems.add(new SearchListItem(173, "Grupo San Francisco"));
        searchListItems.add(new SearchListItem(174, "General Davila 314"));
        searchListItems.add(new SearchListItem(175, "Facultad de Medicina"));
        searchListItems.add(new SearchListItem(176, "Cardenal Herrera Oria 26"));
        searchListItems.add(new SearchListItem(177, "Cardenal Herrera Oria 42"));
        searchListItems.add(new SearchListItem(178, "Cardenal Herrera Oria 76"));
        searchListItems.add(new SearchListItem(179, "Residencia Santa Lucia"));
        searchListItems.add(new SearchListItem(180, "Cardenal Herrera Oria  130"));
        searchListItems.add(new SearchListItem(181, "Avenida del Deporte 15"));
        searchListItems.add(new SearchListItem(355, "Ojaiz"));
        searchListItems.add(new SearchListItem(133, "Camilo Alonso Vega 10"));
        searchListItems.add(new SearchListItem(172, "Camilo Alonso Vega 9"));
        searchListItems.add(new SearchListItem(9, "Valdecilla"));
        searchListItems.add(new SearchListItem(442, "General Davila nº 208"));
        searchListItems.add(new SearchListItem(152, "Bajada la Encina s/n"));
        searchListItems.add(new SearchListItem(184, "Cruce Vicente Trueba"));
        searchListItems.add(new SearchListItem(213, "Avenida de Cantabria 10"));
        searchListItems.add(new SearchListItem(221, "Avenida Cantabria 12"));
        searchListItems.add(new SearchListItem(275, "MataleÇñas"));
        searchListItems.add(new SearchListItem(357, "Avenida Parayas Hotel Expres"));
        searchListItems.add(new SearchListItem(359, "Primero de Mayo"));
        searchListItems.add(new SearchListItem(360, "Manuel Pombo Angulo 10"));
        searchListItems.add(new SearchListItem(361, "Ricardo Lopez Aranda 22"));
        searchListItems.add(new SearchListItem(362, "Primero de Mayo 9"));
        searchListItems.add(new SearchListItem(364, "Pedro San Martin 12"));
        searchListItems.add(new SearchListItem(142, "General Davila 256"));
        searchListItems.add(new SearchListItem(144, "Colegio La Salle"));
        searchListItems.add(new SearchListItem(145, "Camilo Alonso Vega 19"));
        searchListItems.add(new SearchListItem(147, "Marcelino Sanz de Sautuola "));
        searchListItems.add(new SearchListItem(148, "Santa Lucia 26"));
        searchListItems.add(new SearchListItem(149, "Menendez Pelayo 14"));
        searchListItems.add(new SearchListItem(150, "Menendez Pelayo 46"));
        searchListItems.add(new SearchListItem(151, "Menendez Pelayo 76"));
        searchListItems.add(new SearchListItem(134, "Los Pinares"));
        searchListItems.add(new SearchListItem(438, "Cuesta de la Atalaya  2"));
        searchListItems.add(new SearchListItem(153, "Complejo deportivo"));
        searchListItems.add(new SearchListItem(212, "Avenida del Deporte 6"));
        searchListItems.add(new SearchListItem(155, "Lavapies 1"));
        searchListItems.add(new SearchListItem(156, "Calle Repuente 43"));
        searchListItems.add(new SearchListItem(157, "Calle Repuente 26"));
        searchListItems.add(new SearchListItem(158, "Calle Repuente 15"));
        searchListItems.add(new SearchListItem(339, "Barrio la Torre 123"));
        searchListItems.add(new SearchListItem(159, "Barrio la Torre 95"));
        searchListItems.add(new SearchListItem(161, "Jorge Sepulveda 11"));
        searchListItems.add(new SearchListItem(162, "Avenida Cantabria 43"));
        searchListItems.add(new SearchListItem(163, "Padre Menni 1"));
        searchListItems.add(new SearchListItem(164, "Avenida Cantabria 11"));
        searchListItems.add(new SearchListItem(110, "Miranda "));
        searchListItems.add(new SearchListItem(111, "Menendez Pelayo 97"));
        searchListItems.add(new SearchListItem(112, "Menendez Pelayo 61"));
        searchListItems.add(new SearchListItem(113, "Valliciergo 7"));
        searchListItems.add(new SearchListItem(114, "Santa Lucia 1"));
        searchListItems.add(new SearchListItem(115, "Guevara 15"));
        searchListItems.add(new SearchListItem(116, "Plaza de los Remedios"));
        searchListItems.add(new SearchListItem(118, "Camilo Alonso Vega 22"));
        searchListItems.add(new SearchListItem(119, "Camilo Alonso Vega 32"));
        searchListItems.add(new SearchListItem(120, "Las Mercedarias"));
        searchListItems.add(new SearchListItem(122, "General Davila 87"));
        searchListItems.add(new SearchListItem(123, "Los Salesianos"));
        searchListItems.add(new SearchListItem(124, "Prado San Roque"));
        searchListItems.add(new SearchListItem(125, "General DÇ­vila 41"));
        searchListItems.add(new SearchListItem(126, "Santa Clotilde"));
        searchListItems.add(new SearchListItem(127, "Bajada la Encina 1"));
        searchListItems.add(new SearchListItem(128, "Fernando Calderon Rueda 6"));
        searchListItems.add(new SearchListItem(135, "Miranda"));
        searchListItems.add(new SearchListItem(136, "General Davila 28"));
        searchListItems.add(new SearchListItem(137, "General Davila 58"));
        searchListItems.add(new SearchListItem(138, "General Davila 84"));
        searchListItems.add(new SearchListItem(139, "General Davila 122"));
        searchListItems.add(new SearchListItem(140, "Los Salesianos"));
        searchListItems.add(new SearchListItem(141, "General Davila 224"));
        searchListItems.add(new SearchListItem(78, "Cajo 2 Bomberos"));
        searchListItems.add(new SearchListItem(79, "Cajo 10"));
        searchListItems.add(new SearchListItem(80, "Parque Doctor Morales"));
        searchListItems.add(new SearchListItem(81, "Las Californias"));
        searchListItems.add(new SearchListItem(82, "Campogiro 90"));
        searchListItems.add(new SearchListItem(83, "Alto de la PeÇña"));
        searchListItems.add(new SearchListItem(84, "El Empalme 6"));
        searchListItems.add(new SearchListItem(85, "Los Llanos"));
        searchListItems.add(new SearchListItem(86, "Escuelas PeÇñacastillo "));
        searchListItems.add(new SearchListItem(87, "Calle La PeÇña"));
        searchListItems.add(new SearchListItem(88, "Camarreal 109"));
        searchListItems.add(new SearchListItem(89, "Deposito Municipal"));
        searchListItems.add(new SearchListItem(103, "Las Estaciones"));
        searchListItems.add(new SearchListItem(104, "Calle Castilla 27"));
        searchListItems.add(new SearchListItem(105, "Calle Castilla 51"));
        searchListItems.add(new SearchListItem(106, "Calle Castilla71"));
        searchListItems.add(new SearchListItem(107, "Calle Castilla 64"));
        searchListItems.add(new SearchListItem(94, "La Lonja"));
        searchListItems.add(new SearchListItem(95, "Marques de la Hermida 36"));
        searchListItems.add(new SearchListItem(96, "Barrio Pesquero"));
        searchListItems.add(new SearchListItem(321, "Marques de la Hermida 15"));
        searchListItems.add(new SearchListItem(98, "Marques de la Hermida 1"));
        searchListItems.add(new SearchListItem(273, "Estaciones"));
        searchListItems.add(new SearchListItem(129, "Plaza de Italia Casino"));
        searchListItems.add(new SearchListItem(130, "Reina Victoria  117"));
        searchListItems.add(new SearchListItem(132, "Perez Galdos 17"));
        searchListItems.add(new SearchListItem(45, "Avenida de Valdecilla"));
        searchListItems.add(new SearchListItem(46, "Torres Quevedo 22"));
        searchListItems.add(new SearchListItem(47, "Plaza Manuel LLano "));
        searchListItems.add(new SearchListItem(48, "Jose Maria Cossio 12"));
        searchListItems.add(new SearchListItem(49, "Jose Maria Cossio 24"));
        searchListItems.add(new SearchListItem(50, "Jose Maria Cossio 44"));
        searchListItems.add(new SearchListItem(51, "Jose M¶¦ Cossio. 52"));
        searchListItems.add(new SearchListItem(52, "Los Ciruelos 26"));
        searchListItems.add(new SearchListItem(342, "Carrefour Alisal"));
        searchListItems.add(new SearchListItem(341, "Decatlhon"));
        searchListItems.add(new SearchListItem(17, "Castelar"));
        searchListItems.add(new SearchListItem(54, "Barrio de Ojaiz 7"));
        searchListItems.add(new SearchListItem(56, "Camarreal 109"));
        searchListItems.add(new SearchListItem(57, "PeÇñacastillo"));
        searchListItems.add(new SearchListItem(58, "PeÇñacastillo Escuelas"));
        searchListItems.add(new SearchListItem(59, "Los Llanos"));
        searchListItems.add(new SearchListItem(61, "Campogiro 23"));
        searchListItems.add(new SearchListItem(62, "Campogiro"));
        searchListItems.add(new SearchListItem(63, "Campogiro.5"));
        searchListItems.add(new SearchListItem(64, "Cajo 17"));
        searchListItems.add(new SearchListItem(65, "Cajo Renfe"));
        searchListItems.add(new SearchListItem(72, "Rectorado"));
        searchListItems.add(new SearchListItem(197, "Valdenoja 32"));
        searchListItems.add(new SearchListItem(198, "Valdenoja 50"));
        searchListItems.add(new SearchListItem(199, "Manuel Gonzalez Hoyos 7"));
        searchListItems.add(new SearchListItem(333, "Consuelo Berges 22"));
        searchListItems.add(new SearchListItem(326, "Jose Maria Gonzalez Trevilla 4"));
        searchListItems.add(new SearchListItem(337, "Jose Maria Gonzales Trevilla sin numero"));
        searchListItems.add(new SearchListItem(328, "Arsenio Odriozola 16"));
        searchListItems.add(new SearchListItem(330, "Doctor Diego Madrazo"));
        searchListItems.add(new SearchListItem(201, "Concha Espina 18"));
        searchListItems.add(new SearchListItem(167, "Manuel Gonzalez Hoyos 39"));
        searchListItems.add(new SearchListItem(168, "Valdenoja 25"));
        searchListItems.add(new SearchListItem(169, "Valdenoja 3"));
        searchListItems.add(new SearchListItem(29, "Doctor Fleming"));
        searchListItems.add(new SearchListItem(30, "Piquio"));
        searchListItems.add(new SearchListItem(31, "Plaza de Italia"));
        searchListItems.add(new SearchListItem(32, "Luis Martinez"));
        searchListItems.add(new SearchListItem(33, "La Magdalena"));
        searchListItems.add(new SearchListItem(34, "Gonzalez de Riancho"));
        searchListItems.add(new SearchListItem(35, "Reina Victoria 79"));
        searchListItems.add(new SearchListItem(36, "San Martin"));
        searchListItems.add(new SearchListItem(37, "Castelar 29"));
        searchListItems.add(new SearchListItem(38, "Castelar 1"));
        searchListItems.add(new SearchListItem(39, "Paseo de Pereda"));
        searchListItems.add(new SearchListItem(40, "Correos 2"));
        searchListItems.add(new SearchListItem(41, "Plaza Ayuntamiento"));
        searchListItems.add(new SearchListItem(42, "Jesus de Monasterio 12"));
        searchListItems.add(new SearchListItem(43, "San Fernando 22"));
        searchListItems.add(new SearchListItem(44, "San Fernando 66"));
        searchListItems.add(new SearchListItem(280, "Mutua MontaÇñesa"));
        searchListItems.add(new SearchListItem(261, "Casimiro Sainz 6"));
        searchListItems.add(new SearchListItem(262, "Los Escolapios"));
        searchListItems.add(new SearchListItem(263, "Canalejas 26"));
        searchListItems.add(new SearchListItem(264, "Canalejas 42"));
        searchListItems.add(new SearchListItem(345, "Cuesta de la Atalaya 32"));
        searchListItems.add(new SearchListItem(347, "Via Cornelia 32"));
        searchListItems.add(new SearchListItem(348, "Via Cornelia 23"));
        searchListItems.add(new SearchListItem(350, "Calle del Monte 30"));
        searchListItems.add(new SearchListItem(351, "Francisco Palazuelos 13"));
        searchListItems.add(new SearchListItem(346, "Maria Cristina"));
        searchListItems.add(new SearchListItem(16, "Puertochico"));
        searchListItems.add(new SearchListItem(18, "Reina Victoria 18"));
        searchListItems.add(new SearchListItem(19, "Avenida Reina Victoria "));
        searchListItems.add(new SearchListItem(20, "Gonzalez Riancho"));
        searchListItems.add(new SearchListItem(21, "La Magdalena"));
        searchListItems.add(new SearchListItem(22, "Luis Martinez"));
        searchListItems.add(new SearchListItem(23, "Plaza de Italia"));
        searchListItems.add(new SearchListItem(24, "Piquio "));
        searchListItems.add(new SearchListItem(25, "Doctor Fleming "));
        searchListItems.add(new SearchListItem(73, "Los Castros 63"));
        searchListItems.add(new SearchListItem(226, "Los Castros 62"));
        searchListItems.add(new SearchListItem(26, "Los Castros 95"));
        searchListItems.add(new SearchListItem(227, "Los Castros 115"));
        searchListItems.add(new SearchListItem(228, "Bajada San Juan"));
        searchListItems.add(new SearchListItem(229, "Bajada del Caleruco"));
        searchListItems.add(new SearchListItem(230, "Los Castros 136"));
        searchListItems.add(new SearchListItem(231, "Gutierrez Solana 34"));
        searchListItems.add(new SearchListItem(234, "Barrio Hospitalillo 40"));
        searchListItems.add(new SearchListItem(235, "Adarzo"));
        searchListItems.add(new SearchListItem(236, "Rucandial"));
        searchListItems.add(new SearchListItem(239, "Plaza Amador Toca"));
        searchListItems.add(new SearchListItem(240, "Barrio Hospitalillo 97"));
        searchListItems.add(new SearchListItem(274, "Avenida el Faro 20"));
        searchListItems.add(new SearchListItem(244, "Ines Diego Del Noval 50"));
        searchListItems.add(new SearchListItem(245, "Ines Diego De Noval 108"));
        searchListItems.add(new SearchListItem(246, "Ines Diego del Noval 152"));
        searchListItems.add(new SearchListItem(312, "Ermita Cementerio"));
        searchListItems.add(new SearchListItem(248, "Hermanos Toneti 16"));
        searchListItems.add(new SearchListItem(247, "Hermanos Tonetti 8"));
        searchListItems.add(new SearchListItem(249, "Calle Arriba. 85"));
        searchListItems.add(new SearchListItem(250, "Calle Arriba 31"));
        searchListItems.add(new SearchListItem(251, "Residencia Mayores de Cueto"));
        searchListItems.add(new SearchListItem(252, "Cruce de Polio"));
        searchListItems.add(new SearchListItem(254, "Ines Diego Del Noval 61"));
        searchListItems.add(new SearchListItem(256, "Ines Diego Del Noval 25"));
        searchListItems.add(new SearchListItem(255, "Ines Diego De Noval 55"));
        searchListItems.add(new SearchListItem(327, "Jose Maria Gonzalez Trevilla 16"));
        searchListItems.add(new SearchListItem(154, "Avenida del Deporte 11"));
        searchListItems.add(new SearchListItem(214, "Gutierrez Solana 13"));
        searchListItems.add(new SearchListItem(215, "Avenida Los Castros "));
        searchListItems.add(new SearchListItem(216, "Avenida de los Castros nº 155"));
        searchListItems.add(new SearchListItem(217, "Avenida de los Castros 139"));
        searchListItems.add(new SearchListItem(218, "Los Castros 119"));
        searchListItems.add(new SearchListItem(55, "Los Castros 76"));
        searchListItems.add(new SearchListItem(219, "Los Castros 83"));
        searchListItems.add(new SearchListItem(71, "Interfacultativo"));
        searchListItems.add(new SearchListItem(74, "Parque la Teja"));
        searchListItems.add(new SearchListItem(75, "Los Castros 53"));
        searchListItems.add(new SearchListItem(68, "Castros 38"));
        searchListItems.add(new SearchListItem(101, "Los Castros 23"));
        searchListItems.add(new SearchListItem(220, "Torres Quevedo 12"));
        searchListItems.add(new SearchListItem(223, "Gerardo Diego"));
        searchListItems.add(new SearchListItem(224, "Joaquin Bustamante 10"));
        searchListItems.add(new SearchListItem(225, "Joaquin Bustamante 5"));
        searchListItems.add(new SearchListItem(66, "Plaza Brisas"));
        searchListItems.add(new SearchListItem(67, "Los Castros 20"));
        searchListItems.add(new SearchListItem(100, "Los Castros 39"));
        searchListItems.add(new SearchListItem(69, "UIMP"));
        searchListItems.add(new SearchListItem(70, "Escuela Caminos"));
        searchListItems.add(new SearchListItem(381, "Calle Repuente"));
        searchListItems.add(new SearchListItem(53, "Instituto Alisal"));
        searchListItems.add(new SearchListItem(76, "Casimiro Sainz 9"));
        searchListItems.add(new SearchListItem(206, "Barrio La Torre 2"));
        searchListItems.add(new SearchListItem(97, "Parque Varadero"));
        searchListItems.add(new SearchListItem(356, "Plaza de Las Estaciones"));
        searchListItems.add(new SearchListItem(182, "Complejo Ruth Beitia"));
        searchListItems.add(new SearchListItem(183, "Polideportivo"));
        searchListItems.add(new SearchListItem(241, "Cardenal Herrera Oria 119"));
        searchListItems.add(new SearchListItem(185, "Cardenal Herrera Oria 95"));
        searchListItems.add(new SearchListItem(186, "Cardenal Herrera Oria 51"));
        searchListItems.add(new SearchListItem(187, "Cardenal Herrera Oria 31"));
        searchListItems.add(new SearchListItem(188, "Cardenal Herrera Oria 23"));
        searchListItems.add(new SearchListItem(189, "Cardenal Herrera Oria 17"));
        searchListItems.add(new SearchListItem(190, "Cardenal Herrera Oria"));
        searchListItems.add(new SearchListItem(192, "General Davila 117"));
        searchListItems.add(new SearchListItem(194, "Instituto las Llamas"));
        searchListItems.add(new SearchListItem(203, "Padre Menni"));
        searchListItems.add(new SearchListItem(205, "Avenida de Cantabria 100"));
        searchListItems.add(new SearchListItem(207, "Barrio La Torre 60"));
        searchListItems.add(new SearchListItem(340, "Barrio La Torre 76"));
        searchListItems.add(new SearchListItem(208, "Calle Repuente 16"));
        searchListItems.add(new SearchListItem(209, "Calle Repuente"));
        searchListItems.add(new SearchListItem(210, "Calle Repuente 36"));
        searchListItems.add(new SearchListItem(211, "Lavapies 34"));
        searchListItems.add(new SearchListItem(429, "Calle Alta 46"));
        searchListItems.add(new SearchListItem(430, "Calle Alta 56"));
        searchListItems.add(new SearchListItem(431, "Calle Alta 80"));
        searchListItems.add(new SearchListItem(432, "Calle Argentina 7"));
        searchListItems.add(new SearchListItem(433, "Plaza de Toros"));
        searchListItems.add(new SearchListItem(77, "Calvo Sotelo 1"));
        searchListItems.add(new SearchListItem(331, "Corban"));
        searchListItems.add(new SearchListItem(332, "Cruce con Rucandial"));
        searchListItems.add(new SearchListItem(338, "Glorieta de Adarzo"));
        searchListItems.add(new SearchListItem(343, "Joaquin Rodrigo"));
        searchListItems.add(new SearchListItem(1, "Los Ciruelos 47"));
        searchListItems.add(new SearchListItem(2, "Los Ciruelos 27"));
        searchListItems.add(new SearchListItem(3, "Jose M¶¦ Cossio. 54"));
        searchListItems.add(new SearchListItem(4, "Jose Maria Cossio 33"));
        searchListItems.add(new SearchListItem(5, "Jose Maria Cossio 17"));
        searchListItems.add(new SearchListItem(6, "Jose Maria Cossio 1"));
        searchListItems.add(new SearchListItem(7, "Manuel Llano"));
        searchListItems.add(new SearchListItem(8, "Instituto Torres Quevedo"));
        searchListItems.add(new SearchListItem(10, "Cuatro Caminos"));
        searchListItems.add(new SearchListItem(12, "Jesus de Monasterio 21"));
        searchListItems.add(new SearchListItem(13, "Ayuntamiento"));
        searchListItems.add(new SearchListItem(14, "Correos"));
        searchListItems.add(new SearchListItem(15, "Jardines de Pereda"));
        searchListItems.add(new SearchListItem(436, "Pedro San Martin 8"));
        searchListItems.add(new SearchListItem(437, "Emilio Diaz Caneja 2"));
        searchListItems.add(new SearchListItem(279, "Avenida del faro"));
        searchListItems.add(new SearchListItem(293, "Avenida de Parayas ( Chrysler )"));
        searchListItems.add(new SearchListItem(295, "Avenida de Parayas ( Ecrimesa )"));
        searchListItems.add(new SearchListItem(441, "Emilio Diaz Caneja s/n"));
        searchListItems.add(new SearchListItem(354, "Francisco Caceres "));
        searchListItems.add(new SearchListItem(439, "EstaciÇün de autobuses"));
        searchListItems.add(new SearchListItem(281, "General Davila 15"));
        searchListItems.add(new SearchListItem(146, "Catedral"));
        searchListItems.add(new SearchListItem(191, "General Davila 125"));
        searchListItems.add(new SearchListItem(352, "Camarreal 135"));
        searchListItems.add(new SearchListItem(353, "Camarreal 136"));
        searchListItems.add(new SearchListItem(131, "Las Esclavas"));
        searchListItems.add(new SearchListItem(440, "Avenida Vicente Trueba 8"));
        searchListItems.add(new SearchListItem(388, "Virgen del Mar 18"));
        searchListItems.add(new SearchListItem(389, "Virgen del Mar 37"));
        searchListItems.add(new SearchListItem(387, "San Pedro del Mar 51"));
        searchListItems.add(new SearchListItem(276, "Camping"));
        searchListItems.add(new SearchListItem(11, "San Fernando"));
        searchListItems.add(new SearchListItem(426, "Los Peligros"));
        searchListItems.add(new SearchListItem(434, "Calle Alta 28"));
        searchListItems.add(new SearchListItem(307, "Nuevo Parque"));
        searchListItems.add(new SearchListItem(308, "San Martin Del Pino 8"));
        searchListItems.add(new SearchListItem(309, "Santiago el Mayor 9"));
        searchListItems.add(new SearchListItem(310, "Francisco Tomas y Valiente 23"));
        searchListItems.add(new SearchListItem(311, "Francisco Tomas y Valiente 11"));
        searchListItems.add(new SearchListItem(108, "Puente la Marga"));
        searchListItems.add(new SearchListItem(109, "Jeronimo Saiz de la Maza 9"));
        searchListItems.add(new SearchListItem(324, "Plaza de San Martin"));
        searchListItems.add(new SearchListItem(90, "Barrio Las Tejeras"));
        searchListItems.add(new SearchListItem(160, "Barrio La Torre nº 1"));
        return searchListItems;
    }
}
